### ISSUE TITLE
hi talvish

### ISSUE THREAD

**Issue by duplicatedcode** [Talvish/Tales#3]
I'm very interested in tales, is tales have some Architecture diagram, and more detail
tks

**Comment by Talvish** [comment]
I'm afraid there are no architectural diagrams. By far the best way to get an understanding of the system is to use the tales samples repository (to go from basic to larger 'artificial' samples) and the tales rigs repository (for a real world service).  

Admittedly, this doesn't cover the all of the capabilities (e.g. the new security related abilities), but should give a good idea of how things work.

**Comment by duplicatedcode** [comment]
thank you for advice,i like tales
